--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "SberOps";
--
-- Name: SberOps; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "SberOps" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE "SberOps" OWNER TO postgres;

\connect "SberOps"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: SberOperationInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SberOperationInfo" (
    "Id" integer NOT NULL,
    "Added" timestamp with time zone NOT NULL,
    "Deleted" timestamp with time zone,
    "Information" text
);


ALTER TABLE public."SberOperationInfo" OWNER TO postgres;

--
-- Name: SberOperationInfo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SberOperationInfo" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SberOperationInfo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SberOperations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SberOperations" (
    "Id" integer NOT NULL,
    "IdSource" integer,
    "Information" text,
    "Added" timestamp with time zone NOT NULL,
    "TypeWork" integer NOT NULL,
    "Completed" timestamp with time zone
);


ALTER TABLE public."SberOperations" OWNER TO postgres;

--
-- Name: SberOperations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SberOperations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SberOperations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20230710031012_Initial', '7.0.8');


--
-- Name: SberOperationInfo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SberOperationInfo_Id_seq"', 70, true);


--
-- Name: SberOperations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SberOperations_Id_seq"', 70, true);


--
-- Name: SberOperationInfo PK_SberOperationInfo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SberOperationInfo"
    ADD CONSTRAINT "PK_SberOperationInfo" PRIMARY KEY ("Id");


--
-- Name: SberOperations PK_SberOperations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SberOperations"
    ADD CONSTRAINT "PK_SberOperations" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_SberOperations_IdSource; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SberOperations_IdSource" ON public."SberOperations" USING btree ("IdSource");


--
-- Name: SberOperations FK_SberOperations_SberOperationInfo_IdSource; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SberOperations"
    ADD CONSTRAINT "FK_SberOperations_SberOperationInfo_IdSource" FOREIGN KEY ("IdSource") REFERENCES public."SberOperationInfo"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

